"""
data_generator.py — Synthesize realistic test rows from learned ColumnProfiles.

Architecture
────────────
1. PatternAnalyzer provides per-column generation strategies.
2. DataGenerator uses an EXPLICIT FK registry:
   - PROVIDER_FK_MAP contains authoritative FK->PK declarations for every known
     relationship in the Provider schema.  This is merged with heuristic detection
     at startup; explicit entries always take priority.
   - Tracks every generated PK value under its column name.
   - Child FK columns look up their parent pool and pick an existing value.
3. Tables are generated in topological order (parents first, always).
4. If the topological sort cannot satisfy a dependency (e.g. circular), a
   post-generation _fix_orphan_fks() pass repairs any remaining orphans.
5. Zero orphans are guaranteed after the repair pass.

FK Integrity Design
────────────────────
- _pk_registry  : { table_name: { col_name: [generated values] } }
  Stores every PK/unique value generated by a parent table.

- _fk_map : { (child_table, child_col): (parent_table, parent_col) }
  Explicit mapping built once at startup from PROVIDER_FK_MAP + heuristics.

- generate_all() : multi-round loop — defers tables whose parent pools are not
  yet populated until later rounds.

- _fix_orphan_fks() : final safety net — repairs any FK value that is not found
  in the parent pool by replacing it with a random valid parent PK.

- validate_fk_integrity() : post-generation audit returning {(child,col): orphan_count}.
"""
from __future__ import annotations

import csv
import logging
import random
import re
import uuid
from datetime import date, datetime, timedelta
from pathlib import Path
from typing import Any, Optional

from faker import Faker

from pattern_analyzer import (
    ColumnProfile,
    STRAT_DATE, STRAT_ENUM, STRAT_FAKER,
    STRAT_FLOAT_RANGE, STRAT_FREE_TEXT,
    STRAT_INT_RANGE, STRAT_NULL, STRAT_SEQUENTIAL, STRAT_TIMESTAMP,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Oracle month helpers
# ---------------------------------------------------------------------------
_MONTHS = ["JAN","FEB","MAR","APR","MAY","JUN",
           "JUL","AUG","SEP","OCT","NOV","DEC"]

_MONTH_FROM_NUM = {i+1: m for i, m in enumerate(_MONTHS)}
_MONTH_TO_NUM   = {m: i+1 for i, m in enumerate(_MONTHS)}


def _oracle_date_to_date(val: str) -> Optional[date]:
    m = re.match(r"^(\d{1,2})-([A-Za-z]{3})-(\d{2,4})", val.strip())
    if not m:
        return None
    day  = int(m.group(1))
    mon  = _MONTH_TO_NUM.get(m.group(2).upper(), 1)
    year = int(m.group(3))
    if year < 100:
        year = 2000 + year if year < 50 else 1900 + year
    try:
        return date(year, mon, day)
    except ValueError:
        return None


def _iso_date_to_date(val: str) -> Optional[date]:
    try:
        return date.fromisoformat(val[:10])
    except ValueError:
        return None


def _parse_date_bound(val: str) -> Optional[date]:
    return _oracle_date_to_date(val) or _iso_date_to_date(val)


# ---------------------------------------------------------------------------
# FK suffix matching (heuristic fallback — used after explicit map)
# ---------------------------------------------------------------------------

def _strip_prefix(name: str) -> str:
    """Remove leading p_ / g_ / t_ / l_ prefixes."""
    for pre in ("p_", "g_", "t_", "l_"):
        if name.startswith(pre):
            return name[len(pre):]
    return name


def _fk_suffix_matches(child_col: str, parent_col: str) -> bool:
    """
    Return True if child_col looks like a FK to parent_col.

    Rules (highest to lowest priority):
      1. Exact name match               p_sys_id == p_sys_id
      2. Child ends with _<parent_col>  p_grp_sys_id ends with _sys_id
      3. Child ends with _<parent_core> after prefix strip
    """
    if child_col == parent_col:
        return True
    c_core = _strip_prefix(child_col)
    p_core = _strip_prefix(parent_col)
    if c_core.endswith("_" + parent_col):
        return True
    if c_core.endswith("_" + p_core):
        return True
    if c_core == p_core:
        return True
    return False


# ---------------------------------------------------------------------------
# PROVIDER_FK_MAP — Authoritative FK declarations for the Provider schema
#
# Format: { (child_table, child_col): (parent_table, parent_col) }
#
# Derived from the actual Oracle DDL FK constraints and verified against
# sample data.  Takes precedence over heuristic suffix matching.
# ---------------------------------------------------------------------------
PROVIDER_FK_MAP: dict[tuple[str, str], tuple[str, str]] = {
    # P_AFFL_TB: group-member provider affiliation
    ("p_affl_tb",                        "p_grp_sys_id"):        ("p_dtl_tb", "p_sys_id"),
    ("p_affl_tb",                        "p_mbr_sys_id"):        ("p_dtl_tb", "p_sys_id"),
    # P_AFFL_TX: affiliation transaction
    ("p_affl_tx",                        "p_grp_sys_id"):        ("p_dtl_tb", "p_sys_id"),
    ("p_affl_tx",                        "p_mbr_sys_id"):        ("p_dtl_tb", "p_sys_id"),
    # P_ALT_ID_TB
    ("p_alt_id_tb",                      "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_APPL_STAT_TB
    ("p_appl_stat_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_BLNG_MEDM_TB
    ("p_blng_medm_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_CARE_CRD_TX
    ("p_care_crd_tx",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_CLIA tables
    ("p_clia_cert_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_clia_lab_tb",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_clia_prov_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_CMN_LIC_UPLOAD_TB
    ("p_cmn_lic_upload_tb",              "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_COS_STAT_TB
    ("p_cos_stat_tb",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_DSH
    ("p_dsh_tb",                         "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_dsh_tx",                         "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_DTL_TX
    ("p_dtl_tx",                         "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_ELIGIBLE_RECIP_ENTRY_FORM_TN
    ("p_eligible_recip_entry_form_tn",   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_ENROL_AFFL_TB
    ("p_enrol_affl_tb",                  "p_enrol_sys_id"):      ("p_dtl_tb", "p_sys_id"),
    ("p_enrol_affl_tb",                  "p_mbr_sys_id"):        ("p_dtl_tb", "p_sys_id"),
    ("p_enrol_affl_tb",                  "p_grp_sys_id"):        ("p_dtl_tb", "p_sys_id"),
    # P_ENROL_AFFL_TX
    ("p_enrol_affl_tx",                  "p_enrol_sys_id"):      ("p_dtl_tb", "p_sys_id"),
    # P_ENROL_ALT_ID_TB
    ("p_enrol_alt_id_tb",                "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_ENROL_STAT
    ("p_enrol_stat_tb",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_enrol_stat_tx",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_ENROL_TP tables
    ("p_enrol_tp_info_tb",               "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_enrol_tp_txn_info_tb",           "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_EVENT tables
    ("p_event_tb",                       "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_event_rsn_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_event_rsn_tb",                   "p_event_sk"):          ("p_event_tb", "p_event_sk"),
    # P_FACI_TB
    ("p_faci_tb",                        "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_GLBL_ENDRSMNTS
    ("p_glbl_endrsmnts_tn",              "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_glbl_endrsmnts_sought_tn",       "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_HCIDEA hierarchy
    ("p_hcidea_prov_adr_tb",             "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_prov_adr_mcaid_tb",       "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_prov_adr_mcaid_tb",       "p_hcidea_adr_sys_id"): ("p_hcidea_prov_adr_tb", "p_hcidea_adr_sys_id"),
    ("p_hcidea_prov_adr_phone_tb",       "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_prov_adr_phone_tb",       "p_hcidea_adr_sys_id"): ("p_hcidea_prov_adr_tb", "p_hcidea_adr_sys_id"),
    ("p_hcidea_prov_adr_spi_tb",         "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_prov_adr_spi_tb",         "p_hcidea_adr_sys_id"): ("p_hcidea_prov_adr_tb", "p_hcidea_adr_sys_id"),
    ("p_hcidea_prov_deg_tb",             "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_alt_id_tb",               "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_prov_lic_tb",             "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_prov_specl_tb",           "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    ("p_hcidea_prov_txnmy_tb",           "p_hcidea_sys_id"):     ("p_hcidea_prov_tb", "p_hcidea_sys_id"),
    # P_IF tables
    ("p_if_1915i_tb",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_if_pt_ps_tb",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_if_sandata_tb",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_if_therap_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_INTERP_SVC_TB
    ("p_interp_svc_tb",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_LANG_TB
    ("p_lang_tb",                        "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_LIC_CERT_TB
    ("p_lic_cert_tb",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_LTR_REQ_TB
    ("p_ltr_req_tb",                     "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_MCARE_TB
    ("p_mcare_tb",                       "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_MC_PRTCPTN_TN
    ("p_mc_prtcptn_tn",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_NONMED_PROV_RECIP_TN
    ("p_nonmed_prov_recip_tn",           "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_NPPES tables
    ("p_nppes_npi_src_other_id_tb",      "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_nppes_npi_src_txnmy_tb",         "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_NUM_BED_TB
    ("p_num_bed_tb",                     "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_NW_PART_TB
    ("p_nw_part_tb",                     "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_OFC_HRS_TB
    ("p_ofc_hrs_tb",                     "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_OIG tables
    ("p_oig_prov_match_tb",              "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_oig_prov_xref_tb",               "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_OWNER_XREF_TB
    ("p_owner_xref_tb",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_OWNRSHP_CHG_REQ_TN
    ("p_ownrshp_chg_req_tn",             "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_PBM_NW_PRTCPTN_TB
    ("p_pbm_nw_prtcptn_tb",              "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_pbm_nw_prtcptn_tb",              "p_nw_part_sk"):        ("p_nw_part_tb", "p_nw_part_sk"),
    # P_PREV_MCAID_TB
    ("p_prev_mcaid_tb",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_PREV_NAM_TN
    ("p_prev_nam_tn",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_PROG_INFO_REQ_TB
    ("p_prog_info_req_tb",               "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_PROV_CNTY_TN
    ("p_prov_cnty_tn",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_QSP tables
    ("p_qsp_prov_recip_tn",              "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_qsp_qstnr_initialed_resp_tn",    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_qsp_qstnr_tn",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_QSTNR tables
    ("p_qstnr_advrs_legal_actn_tb",      "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_qstnr_exclsn_tb",                "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_qstnr_other_state_tb",           "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_qstnr_ovr_pmt_tb",               "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_qstnr_tb",                       "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_RA_MEDM tables
    ("p_ra_medm_tb",                     "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_ra_medm_tx",                     "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_REQ_ATTACH_TB
    ("p_req_attach_tb",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_REVAL_STAT_TN
    ("p_reval_stat_tn",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_RPT_PHARM_UPD_TB
    ("p_rpt_pharm_upd_tb",               "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_RSK_SCRN_TN
    ("p_rsk_scrn_tn",                    "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_SPECL tables
    ("p_specl_need_tb",                  "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    ("p_specl_tb",                       "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_SVC_TY_CD_TB
    ("p_svc_ty_cd_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_TAX_NTC_TB
    ("p_tax_ntc_tb",                     "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_TXNMY_TB
    ("p_txnmy_tb",                       "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_TY_TB
    ("p_ty_tb",                          "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
    # P_WEB_DSPLY_TB
    ("p_web_dsply_tb",                   "p_sys_id"):            ("p_dtl_tb", "p_sys_id"),
}


# ---------------------------------------------------------------------------
# DataGenerator
# ---------------------------------------------------------------------------

class DataGenerator:
    """
    Generates synthetic rows for all tables using learned ColumnProfiles.

    FK integrity is maintained via a three-layer approach:
    1. PROVIDER_FK_MAP — explicit FK declarations (highest priority).
    2. Heuristic suffix matching for any remaining FK relationships.
    3. _fix_orphan_fks() — post-generation repair guaranteeing zero orphans.
    """

    def __init__(
        self,
        profiles      : dict[str, dict[str, ColumnProfile]],
        output_dir    : Path,
        rows_per_table: int = 1000,
        seed          : int = 12345,
    ) -> None:
        self._profiles  = profiles
        self._out_dir   = output_dir
        self._rows      = rows_per_table
        self._seed      = seed

        random.seed(seed)
        self._fake = Faker()
        Faker.seed(seed)

        self._out_dir.mkdir(parents=True, exist_ok=True)

        # PK registry: { table_name -> { col_name -> [generated values] } }
        self._pk_registry: dict[str, dict[str, list[Any]]] = {}

        # FK map: { (child_table, child_col) -> (parent_table, parent_col) }
        self._fk_map: dict[tuple[str, str], tuple[str, str]] = {}

        # Uniqueness registry for columns that must not repeat
        self._unique_registry: dict[str, set[Any]] = {}

        self._parent_of: dict[str, tuple[str, str]] = {}
        self._order = self._build_fk_map_and_order()

    # ------------------------------------------------------------------ #
    # Public                                                               #
    # ------------------------------------------------------------------ #

    def generate_all(self) -> dict[str, int]:
        """
        Generate all tables using a multi-round deferred strategy.

        A table is deferred when any of its FK parent pools are not yet
        populated.  After all rounds, _fix_orphan_fks() repairs any remaining
        orphan values.  Zero orphans are guaranteed.
        """
        results: dict[str, int] = {}
        remaining = [t for t in self._order if t in self._profiles]
        max_rounds = len(remaining) + 2

        for round_num in range(max_rounds):
            if not remaining:
                break

            generated_this_round: list[str] = []
            deferred: list[str] = []

            for table in remaining:
                if self._is_table_ready(table):
                    try:
                        count = self._generate_table(table)
                        results[table] = count
                        logger.info(
                            "  [R%d] Generated %d rows for %s.",
                            round_num + 1, count, table,
                        )
                    except Exception as exc:  # noqa: BLE001
                        logger.error("  Failed %s: %s", table, exc, exc_info=True)
                        results[table] = 0
                    generated_this_round.append(table)
                else:
                    deferred.append(table)

            if not generated_this_round and deferred:
                # No progress — break cycle by forcing deferred tables
                logger.warning(
                    "No progress; forcing %d deferred tables: %s",
                    len(deferred), deferred,
                )
                for table in deferred:
                    try:
                        count = self._generate_table(table)
                        results[table] = count
                        logger.info("  [Force] Generated %d rows for %s.", count, table)
                    except Exception as exc:  # noqa: BLE001
                        logger.error("  Failed %s: %s", table, exc, exc_info=True)
                        results[table] = 0
                remaining = []
                break

            remaining = deferred

        # Post-generation FK orphan repair
        logger.info("Post-generation FK orphan repair pass ...")
        repaired = self._fix_orphan_fks()
        if repaired:
            logger.warning("  Repaired %d orphan FK values.", repaired)
        else:
            logger.info("  FK integrity OK — zero orphans.")

        return results

    def generate_one(self, table_name: str) -> int:
        return self._generate_table(table_name)

    def output_path(self, table_name: str) -> Path:
        return self._out_dir / f"{table_name.upper()}.csv"

    def validate_fk_integrity(self) -> dict[tuple[str, str], int]:
        """
        Post-generation FK audit.
        Returns { (child_table, child_col): orphan_count } for broken FKs.
        An empty dict means perfect referential integrity.
        """
        report: dict[tuple[str, str], int] = {}
        for (child_tbl, child_col), (parent_tbl, parent_col) in self._fk_map.items():
            parent_pool = set(
                str(v) for v in
                self._pk_registry.get(parent_tbl, {}).get(parent_col, [])
            )
            if not parent_pool:
                continue

            csv_path = self.output_path(child_tbl)
            if not csv_path.exists():
                continue

            with open(csv_path, newline="", encoding="utf-8") as fh:
                rows = list(csv.DictReader(fh))

            child_vals = [
                str(r.get(child_col, "") or "")
                for r in rows
                if r.get(child_col, "")
            ]
            orphans = [v for v in child_vals if v not in parent_pool]
            if orphans:
                report[(child_tbl, child_col)] = len(orphans)
                logger.warning(
                    "  FK ORPHANS: %s.%s -> %s.%s : %d/%d are orphans",
                    child_tbl, child_col, parent_tbl, parent_col,
                    len(orphans), len(child_vals),
                )
        return report

    # ------------------------------------------------------------------ #
    # FK Map Construction                                                  #
    # ------------------------------------------------------------------ #

    def _is_table_ready(self, table: str) -> bool:
        """Return True if all FK parent pools for this table are populated."""
        for col in self._profiles.get(table, {}):
            mapping = self._fk_map.get((table, col))
            if mapping:
                p_tbl, p_col = mapping
                if not self._pk_registry.get(p_tbl, {}).get(p_col, []):
                    return False
        return True

    def _identify_pk_columns(self) -> dict[str, tuple[str, str]]:
        """
        For each column name that appears in multiple tables, decide which
        single table is the authoritative parent (PK owner).
        """
        col_table_map: dict[str, set[str]] = {}
        for tbl, cols in self._profiles.items():
            for col in cols:
                col_table_map.setdefault(col, set()).add(tbl)

        parent_of: dict[str, tuple[str, str]] = {}

        for col, tables in col_table_map.items():
            if len(tables) == 1:
                only_tbl = next(iter(tables))
                parent_of[col] = (only_tbl, col)
                continue

            best_tbl   = None
            best_score = -9999.0

            for tbl in tables:
                prof  = self._profiles[tbl][col]
                score = 0.0

                if prof.strategy == STRAT_SEQUENTIAL:
                    score += 25.0
                if prof.is_unique:
                    score += 15.0
                elif prof.strategy == STRAT_INT_RANGE:
                    score += 5.0

                tbl_stem = tbl.lower()
                for pre in ("p_", "g_", "t_", "l_"):
                    if tbl_stem.startswith(pre):
                        tbl_stem = tbl_stem[len(pre):]
                for suf in ("_tb", "_tx", "_tn"):
                    if tbl_stem.endswith(suf):
                        tbl_stem = tbl_stem[: -len(suf)]

                has_own_surrogate = False
                for other_col in self._profiles[tbl]:
                    if other_col == col:
                        continue
                    oc = _strip_prefix(other_col)
                    if oc in (f"{tbl_stem}_sk", f"{tbl_stem}_sys_id", f"{tbl_stem}_id"):
                        has_own_surrogate = True
                        break

                if has_own_surrogate:
                    score -= 20.0
                else:
                    score += 30.0

                if prof.strategy == STRAT_SEQUENTIAL and prof.int_start > 0:
                    score -= prof.int_start / 1_000_000_000.0

                if score > best_score:
                    best_score = score
                    best_tbl   = tbl

            if best_tbl:
                parent_of[col] = (best_tbl, col)

        return parent_of

    def _build_fk_map_and_order(self) -> list[str]:
        """
        Build self._fk_map and return tables in topological order.

        Layer 1: PROVIDER_FK_MAP (explicit, authoritative).
        Layer 2: Heuristic suffix matching for remaining columns.
        """
        all_tables = list(self._profiles.keys())
        self._parent_of = self._identify_pk_columns()

        deps: dict[str, set[str]] = {t: set() for t in all_tables}
        self._fk_map = {}

        # Layer 1 — explicit map
        for (child_tbl, child_col), (p_tbl, p_col) in PROVIDER_FK_MAP.items():
            if (child_tbl not in self._profiles
                    or child_col not in self._profiles.get(child_tbl, {})
                    or p_tbl not in self._profiles):
                continue
            self._fk_map[(child_tbl, child_col)] = (p_tbl, p_col)
            deps[child_tbl].add(p_tbl)
            logger.debug("FK [explicit]: %s.%s -> %s.%s", child_tbl, child_col, p_tbl, p_col)

        # Layer 2 — heuristic suffix matching
        for child_tbl in all_tables:
            for child_col in self._profiles[child_tbl]:
                if (child_tbl, child_col) in self._fk_map:
                    continue
                for p_col, (p_tbl, _) in self._parent_of.items():
                    if p_tbl == child_tbl:
                        continue
                    if _fk_suffix_matches(child_col, p_col):
                        self._fk_map[(child_tbl, child_col)] = (p_tbl, p_col)
                        deps[child_tbl].add(p_tbl)
                        logger.debug(
                            "FK [heuristic]: %s.%s -> %s.%s",
                            child_tbl, child_col, p_tbl, p_col,
                        )
                        break

        # Topological sort (Kahn's algorithm)
        in_deg = {t: len(deps[t]) for t in all_tables}
        queue  = [t for t in all_tables if in_deg[t] == 0]
        order: list[str] = []

        while queue:
            node = queue.pop(0)
            order.append(node)
            for t in all_tables:
                if node in deps[t]:
                    deps[t].discard(node)
                    in_deg[t] -= 1
                    if in_deg[t] == 0:
                        queue.append(t)

        for t in all_tables:
            if t not in order:
                order.append(t)

        explicit_count   = sum(1 for k in self._fk_map if k in PROVIDER_FK_MAP)
        heuristic_count  = len(self._fk_map) - explicit_count
        logger.info(
            "FK map: %d total (%d explicit + %d heuristic) across %d tables.",
            len(self._fk_map), explicit_count, heuristic_count, len(all_tables),
        )
        return order

    # ------------------------------------------------------------------ #
    # Table generation                                                     #
    # ------------------------------------------------------------------ #

    def _generate_table(self, table_name: str) -> int:
        profiles = self._profiles[table_name]
        columns  = list(profiles.keys())
        out_path = self.output_path(table_name)

        fk_info: dict[str, tuple[str, str]] = {}
        for col in columns:
            mapping = self._fk_map.get((table_name, col))
            if mapping:
                p_tbl, p_col = mapping
                if (
                    p_tbl in self._pk_registry
                    and p_col in self._pk_registry[p_tbl]
                    and self._pk_registry[p_tbl][p_col]
                ):
                    fk_info[col] = (p_tbl, p_col)
                else:
                    logger.debug(
                        "FK %s.%s -> %s.%s: parent pool empty; will repair later.",
                        table_name, col, p_tbl, p_col,
                    )

        seq_state: dict[str, int] = {
            col: prof.int_start
            for col, prof in profiles.items()
            if prof.strategy == STRAT_SEQUENTIAL
        }

        rows: list[dict[str, Any]] = []
        for _ in range(self._rows):
            row: dict[str, Any] = {}
            for col in columns:
                prof = profiles[col]
                row[col] = self._generate_cell(
                    table_name, col, prof, fk_info, seq_state
                )
            self._apply_row_constraints(row, profiles)
            for col in columns:
                if isinstance(row[col], (date, datetime)):
                    row[col] = self._format_date_val(row[col], profiles[col])
            rows.append(row)

        with open(out_path, "w", newline="", encoding="utf-8") as fh:
            writer = csv.DictWriter(fh, fieldnames=columns, quoting=csv.QUOTE_ALL)
            writer.writeheader()
            writer.writerows(rows)

        self._register_pk_values(table_name, profiles, rows)
        return len(rows)

    def _register_pk_values(
        self,
        table_name: str,
        profiles  : dict[str, ColumnProfile],
        rows      : list[dict[str, Any]],
    ) -> None:
        self._pk_registry.setdefault(table_name, {})
        for col, prof in profiles.items():
            if prof.strategy == STRAT_SEQUENTIAL or prof.is_unique:
                vals = [r[col] for r in rows if r[col] is not None]
                if vals:
                    self._pk_registry[table_name].setdefault(col, []).extend(vals)

    # ------------------------------------------------------------------ #
    # Post-generation FK orphan repair                                     #
    # ------------------------------------------------------------------ #

    def _fix_orphan_fks(self) -> int:
        """
        Replace every orphan FK value with a valid parent PK.
        Rewrites the CSV for any table that has orphans.
        Returns total count of repaired values.
        """
        total_repaired = 0

        for (child_tbl, child_col), (parent_tbl, parent_col) in self._fk_map.items():
            parent_pool = [
                str(v) for v in
                self._pk_registry.get(parent_tbl, {}).get(parent_col, [])
            ]
            if not parent_pool:
                continue

            csv_path = self.output_path(child_tbl)
            if not csv_path.exists():
                continue

            with open(csv_path, newline="", encoding="utf-8") as fh:
                reader  = csv.DictReader(fh)
                headers = reader.fieldnames or []
                rows    = list(reader)

            if child_col not in headers:
                continue

            parent_set = set(parent_pool)
            repaired   = 0
            for row in rows:
                val = row.get(child_col, "")
                if val and str(val) not in parent_set:
                    row[child_col] = random.choice(parent_pool)
                    repaired += 1

            if repaired:
                logger.debug(
                    "  Repaired %d orphans in %s.%s", repaired, child_tbl, child_col
                )
                with open(csv_path, "w", newline="", encoding="utf-8") as fh:
                    writer = csv.DictWriter(fh, fieldnames=headers, quoting=csv.QUOTE_ALL)
                    writer.writeheader()
                    writer.writerows(rows)
                total_repaired += repaired

        return total_repaired

    # ------------------------------------------------------------------ #
    # Single cell generation                                               #
    # ------------------------------------------------------------------ #

    def _generate_cell(
        self,
        table_name: str,
        col       : str,
        prof      : ColumnProfile,
        fk_info   : dict[str, tuple[str, str]],
        seq_state : dict[str, int],
    ) -> Any:
        if col in fk_info:
            p_tbl, p_col = fk_info[col]
            pool = self._pk_registry.get(p_tbl, {}).get(p_col, [])
            if pool:
                if prof.null_rate > 0 and random.random() < prof.null_rate:
                    return None
                return random.choice(pool)

        for attempt in range(150):
            val = self._generate_raw(col, prof, seq_state)
            if val is None:
                return None
            if not prof.is_unique:
                return val
            reg = self._unique_registry.setdefault(col, set())
            if val not in reg:
                reg.add(val)
                return val
        return val

    def _generate_raw(
        self,
        col      : str,
        prof     : ColumnProfile,
        seq_state: dict[str, int],
    ) -> Any:
        if prof.null_rate > 0 and random.random() < prof.null_rate:
            return None

        s = prof.strategy

        if s == STRAT_NULL:
            return None
        if s == STRAT_SEQUENTIAL:
            seq_state[col] += prof.int_step
            return seq_state[col]
        if s == STRAT_INT_RANGE:
            return random.randint(prof.int_min, max(prof.int_max, prof.int_min))
        if s == STRAT_FLOAT_RANGE:
            return round(random.uniform(prof.float_min, prof.float_max), 2)
        if s == STRAT_ENUM:
            if not prof.sample_values:
                return None
            return random.choices(prof.sample_values, weights=prof.weights, k=1)[0]
        if s == STRAT_DATE:
            return self._random_date(prof)
        if s == STRAT_TIMESTAMP:
            return self._random_timestamp(prof)
        if s == STRAT_FAKER:
            val = self._call_faker(prof.faker_tag, prof.max_length)
            if prof.strip_non_digits:
                val = re.sub(r"\D", "", val)
            if prof.max_length and len(val) > prof.max_length:
                val = val[: prof.max_length]
            return val
        if s == STRAT_FREE_TEXT:
            if not prof.sample_values:
                return None
            return random.choice(prof.sample_values)
        return None

    # ------------------------------------------------------------------ #
    # Date helpers                                                         #
    # ------------------------------------------------------------------ #

    def _random_date(self, prof: ColumnProfile) -> date:
        d_min = _parse_date_bound(prof.date_min) or date(2000, 1, 1)
        d_max = _parse_date_bound(prof.date_max) or date(2030, 12, 31)
        if d_min > d_max:
            d_min, d_max = d_max, d_min
        delta = (d_max - d_min).days
        return d_min + timedelta(days=random.randint(0, max(delta, 0)))

    def _random_timestamp(self, prof: ColumnProfile) -> datetime:
        d_min = _parse_date_bound(prof.date_min) or date(2000, 1, 1)
        d_max = _parse_date_bound(prof.date_max) or date(2030, 12, 31)
        if d_min > d_max:
            d_min, d_max = d_max, d_min
        delta_days = (d_max - d_min).days
        rand_d = d_min + timedelta(days=random.randint(0, max(delta_days, 0)))
        return datetime(
            rand_d.year, rand_d.month, rand_d.day,
            random.randint(0, 23),
            random.randint(0, 59),
            random.randint(0, 59),
            random.randint(0, 999999),
        )

    # ------------------------------------------------------------------ #
    # Row constraints                                                      #
    # ------------------------------------------------------------------ #

    def _apply_row_constraints(
        self,
        row     : dict[str, Any],
        profiles: dict[str, ColumnProfile],
    ) -> None:
        from config import AUDIT_USER

        for col in row:
            if col in ("g_aud_user_id", "g_aud_add_user_id",
                       "g_aud_upd_user_id", "g_web_user_id"):
                row[col] = AUDIT_USER

        now_dt  = datetime.now()
        add_col = next((c for c in row if c == "g_aud_add_ts"), None)
        aud_col = next((c for c in row if c == "g_aud_ts"), None)

        if add_col and row[add_col] is not None:
            row[add_col] = now_dt - timedelta(
                days=random.randint(1, 365),
                seconds=random.randint(0, 86400),
            )
        if aud_col and row[aud_col] is not None:
            base = row[add_col] if (add_col and row[add_col] is not None) else now_dt
            row[aud_col] = base + timedelta(
                days=random.randint(0, 30),
                seconds=random.randint(0, 86400),
            )

        begin_patterns = ["beg_dt", "start_dt", "eff_dt", "add_dt"]
        end_patterns   = ["end_dt", "term_dt", "cancel_dt", "rever_dt"]

        begins = [c for c in row if isinstance(row[c], (date, datetime))
                  and any(p in c for p in begin_patterns)]
        ends   = [c for c in row if isinstance(row[c], (date, datetime))
                  and any(p in c for p in end_patterns)]

        for b_col in begins:
            for e_col in ends:
                b_val = row[b_col]
                e_val = row[e_col]
                if b_val and e_val:
                    b_d = b_val.date() if isinstance(b_val, datetime) else b_val
                    e_d = e_val.date() if isinstance(e_val, datetime) else e_val
                    if e_d <= b_d:
                        new_e = b_d + timedelta(days=random.randint(30, 365 * 5))
                        row[e_col] = (
                            datetime.combine(new_e, e_val.time())
                            if isinstance(e_val, datetime)
                            else new_e
                        )

    def _format_date_val(self, val: date | datetime, prof: ColumnProfile) -> str:
        if isinstance(val, datetime):
            if prof.is_oracle_fmt:
                mon = _MONTH_FROM_NUM[val.month]
                h12 = val.hour % 12 or 12
                mer = "AM" if val.hour < 12 else "PM"
                ns  = val.microsecond * 1000
                return (
                    f"{val.day:02d}-{mon}-{str(val.year)[-2:]:>02s} "
                    f"{h12:02d}.{val.minute:02d}.{val.second:02d}.{ns:09d} {mer}"
                )
            return val.strftime("%Y-%m-%d %H:%M:%S.%f")
        else:
            if prof.is_oracle_fmt:
                mon = _MONTH_FROM_NUM[val.month]
                return f"{val.day:02d}-{mon}-{str(val.year)[-2:]:>02s}"
            return val.isoformat()

    # ------------------------------------------------------------------ #
    # Faker dispatch                                                        #
    # ------------------------------------------------------------------ #

    def _call_faker(self, tag: str, max_length: int) -> str:
        fake = self._fake
        if tag == "license":
            return f"ND{random.randint(100000, 9999999)}"
        if tag == "npi":
            return str(random.choice([1, 2])) + "".join(
                str(random.randint(0, 9)) for _ in range(9)
            )
        if tag == "dea":
            first  = random.choice(["A", "B", "F", "G", "M", "P"])
            second = random.choice("ABCDEFGHIJKLMNOPQRSTUVWXYZ")
            digits = [random.randint(0, 9) for _ in range(6)]
            total  = (digits[0] + digits[2] + digits[4]) + 2 * (digits[1] + digits[3] + digits[5])
            digits.append(total % 10)
            return f"{first}{second}{''.join(map(str, digits))}"
        if tag == "tin":
            return "".join(str(random.randint(0, 9)) for _ in range(9))
        if tag == "uuid":
            return str(uuid.uuid4())
        if tag == "provider_id":
            return fake.bothify("??#######").upper()

        dispatch: dict[str, Any] = {
            "last_name"     : fake.last_name,
            "first_name"    : fake.first_name,
            "name"          : fake.name,
            "street_address": fake.street_address,
            "city"          : fake.city,
            "state_abbr"    : fake.state_abbr,
            "zipcode"       : fake.zipcode,
            "phone_number"  : fake.phone_number,
            "email"         : fake.email,
            "url"           : fake.url,
            "company"       : fake.company,
            "date_of_birth" : lambda: fake.date_of_birth().strftime("%Y-%m-%d"),
        }
        fn = dispatch.get(tag)
        if fn is None:
            return fake.word()
        return str(fn())
