--------------------------------------------------------
--  DDL for Table P_CARE_CRD_TX
--------------------------------------------------------

  CREATE TABLE "P_CARE_CRD_TX" ("P_SYS_ID" NUMBER(10,0), "P_CARE_CRD_SK" NUMBER(10,0), "P_CARE_CRD_CD" VARCHAR2(6), "P_CARE_CRD_BEG_DT" DATE, "P_CARE_CRD_END_DT" DATE, "P_CARE_VOID_INDR" VARCHAR2(1), "L_HIBERNATE_VER_NUM" NUMBER(9,0), "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
