--------------------------------------------------------
--  DDL for Table P_CMN_LIC_UPLOAD_TB
--------------------------------------------------------

  CREATE TABLE "P_CMN_LIC_UPLOAD_TB" ("P_LIC_CERT_NUM" VARCHAR2(10), "P_CMN_LIC_ACTN_CD" VARCHAR2(1), "P_CMN_LIC_SSN_NUM" VARCHAR2(9), "P_CMN_LIC_FIRST_NAM" VARCHAR2(25), "P_CMN_LIC_LAST_NAM" VARCHAR2(35), "P_CMN_LIC_MID_NAM" VARCHAR2(25), "P_LIC_CERT_CD" VARCHAR2(4), "P_CMN_LIC_CERT_BEG_DT" DATE, "P_CMN_LIC_CERT_END_DT" DATE, "P_LIC_RSTRCT_CD" VARCHAR2(1), "P_CMN_LIC_CERT_STAT_CD" VARCHAR2(1), "P_LIC_CERT_AGCY_CD" VARCHAR2(3), "P_CMN_LIC_CERT_FACI_NAM" VARCHAR2(60), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
