--------------------------------------------------------
--  DDL for Table P_DTL_TX
--------------------------------------------------------

  CREATE TABLE "P_DTL_TX" ("P_SYS_ID" NUMBER(10,0), "P_PROV_AGMT_READ_IND" VARCHAR2(1) DEFAULT 'N', "P_PCCM_AGMT_READ_IND" VARCHAR2(1) DEFAULT 'N', "P_REQ_CLM_SUBM_EFF_DT" DATE, "P_QSP_LAST_GRADE_COMPLETED_CD" VARCHAR2(5), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30), "P_340B_IND" VARCHAR2(1) DEFAULT 'N', "P_1099_IND" VARCHAR2(1) DEFAULT 'Y', "P_SVC_AREA_DSTNC_CD" VARCHAR2(3), "P_PUB_PROV_IND" VARCHAR2(1) DEFAULT 'N', "P_TP_AGMT_READ_IND" VARCHAR2(1) DEFAULT 'N', "P_WEBSITE" VARCHAR2(50), "P_ACCEPT_NEW" VARCHAR2(1), "P_TELEHEALTH" VARCHAR2(1), "P_OTHER_ACCOM" VARCHAR2(25))
