--------------------------------------------------------
--  DDL for Table P_ELIGIBLE_RECIP_ENTRY_FORM_TN
--------------------------------------------------------

  CREATE TABLE "P_ELIGIBLE_RECIP_ENTRY_FORM_TN" ("P_SYS_ID" NUMBER(10,0), "P_RECIP_SEQ_NUM" NUMBER(5,0), "P_MCAID_ID" VARCHAR2(10), "P_RECIPIENT_FIRST_NAM" VARCHAR2(25), "P_RECIPIENT_LAST_NAME" VARCHAR2(35), "P_RECIP_MI_NAM" VARCHAR2(1), "P_RESIDE_IN_HSEHLD_IND" VARCHAR2(1) DEFAULT 'Y', "P_FOST_CHILD_IND" VARCHAR2(1) DEFAULT 'N', "P_RECIP_REL_CD" VARCHAR2(5), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30), "P_RECIP_SFX_NAM" VARCHAR2(10), "P_HSEHLD_RESP_TEXT" VARCHAR2(4000), "B_MCAID_ID" VARCHAR2(15), "B_SYS_ID" NUMBER(10,0))
