--------------------------------------------------------
--  DDL for Table P_ENROL_STAT_TX
--------------------------------------------------------

  CREATE TABLE "P_ENROL_STAT_TX" ("P_SYS_ID" NUMBER(10,0), "P_ENROL_STAT_SK" NUMBER(10,0), "P_DISENROL_STAT_TY_CD" VARCHAR2(2), "P_DISENROL_STAT_BEG_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
