--------------------------------------------------------
--  DDL for Table P_GLBL_ENDRSMNTS_SOUGHT_TN
--------------------------------------------------------

  CREATE TABLE "P_GLBL_ENDRSMNTS_SOUGHT_TN" ("P_SYS_ID" NUMBER(10,0), "P_ENDRSMNT_CD" VARCHAR2(5), "P_ENDRSMNT_NAM" VARCHAR2(40), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
