--------------------------------------------------------
--  DDL for Table P_HCIDEA_ALT_ID_TB
--------------------------------------------------------

  CREATE TABLE "P_HCIDEA_ALT_ID_TB" ("P_HCIDEA_ALT_ID" VARCHAR2(20), "P_HCIDEA_ALT_ID_TY_CD" VARCHAR2(4), "P_HCIDEA_SYS_ID" NUMBER(10,0), "P_HCIDEA_CO_CNT" NUMBER(5,0), "P_HCIDEA_TIER_CD" VARCHAR2(2), "P_HCIDEA_VRFY_CD" VARCHAR2(2), "P_HCIDEA_VFRY_DT" DATE, "P_HCIDEA_DEA_STAT_CD" VARCHAR2(1), "P_HCIDEA_DEA_DRUG_SCHDL_DATA" VARCHAR2(16), "P_HCIDEA_DEA_RNWL_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30))
