--------------------------------------------------------
--  DDL for Table P_HCIDEA_PROV_ADR_MCAID_TB
--------------------------------------------------------

  CREATE TABLE "P_HCIDEA_PROV_ADR_MCAID_TB" ("P_HCIDEA_SYS_ID" NUMBER(10,0), "P_HCIDEA_ADR_SYS_ID" NUMBER(10,0), "P_HCIDEA_MCAID_STATE_CD" VARCHAR2(2), "P_HCIDEA_MCAID_ID" VARCHAR2(20), "P_HCIDEA_MCAID_CO_CNT" NUMBER(5,0), "P_HCIDEA_MCAID_TIER_CD" VARCHAR2(2), "P_HCIDEA_MCAID_VRFY_CD" VARCHAR2(2), "P_HCIDEA_MCAID_VRFY_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30))
