--------------------------------------------------------
--  DDL for Table P_HCIDEA_PROV_TXNMY_TB
--------------------------------------------------------

  CREATE TABLE "P_HCIDEA_PROV_TXNMY_TB" ("P_HCIDEA_SYS_ID" NUMBER(10,0), "P_HCIDEA_TXNMY_SEQ_NUM" NUMBER(3,0), "P_HCIDEA_TXNMY_CD" VARCHAR2(10), "P_HCIDEA_PRIM_TXNMY_CD" VARCHAR2(1), "P_HCIDEA_TXNMY_DESC" VARCHAR2(400), "P_HCIDEA_TXNMY_CO_CNT" NUMBER(5,0), "P_HCIDEA_TXNMY_TIER_CD" VARCHAR2(2), "P_HCIDEA_TXNMY_VRFY_CD" VARCHAR2(2), "P_HCIDEA_TXNMY_VRFY_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30))
