--------------------------------------------------------
--  DDL for Table P_HCIDEA_PROV_LIC_TB
--------------------------------------------------------

  CREATE TABLE "P_HCIDEA_PROV_LIC_TB" ("P_HCIDEA_SYS_ID" NUMBER(10,0), "P_HCIDEA_LIC_SEQ_NUM" NUMBER(3,0), "P_HCIDEA_LIC_NUM" VARCHAR2(50), "P_HCIDEA_LIC_STATE_CD" VARCHAR2(2), "P_HCIDEA_LIC_ISSUE_DT" DATE, "P_HCIDEA_LIC_EXPIR_DT" DATE, "P_HCIDEA_LIC_CO_CNT" NUMBER(5,0), "P_HCIDEA_LIC_TIER_CD" VARCHAR2(2), "P_HCIDEA_LIC_VRFY_CD" VARCHAR2(2), "P_HCIDEA_LIC_VRFY_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30))
