--------------------------------------------------------
--  DDL for Table P_MC_PRTCPTN_TN
--------------------------------------------------------

  CREATE TABLE "P_MC_PRTCPTN_TN" ("P_SYS_ID" NUMBER(10,0), "P_MC_PRTCPTN_PROG_CD" VARCHAR2(1), "P_MC_PROG_PRTCPTN_BEG_DT" DATE, "P_MC_PROG_PRTCPTN_END_DT" DATE, "P_MC_STAT_CD" VARCHAR2(2), "P_MC_PRTCPTN_RSN_CD" VARCHAR2(3), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30), "P_MC_MAX_MBR_CNT" NUMBER(5,0) DEFAULT 250, "P_MC_ACT_MBR_CNT" NUMBER(5,0) DEFAULT 0)
