--------------------------------------------------------
--  DDL for Table P_NONMED_PROV_RECIP_TN
--------------------------------------------------------

  CREATE TABLE "P_NONMED_PROV_RECIP_TN" ("P_SYS_ID" NUMBER(10,0), "G_CNTY_CD" VARCHAR2(5), "P_SCRN_LOCN_CD" VARCHAR2(1), "B_SYS_ID" NUMBER(10,0), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0)
