--------------------------------------------------------
--  DDL for Table P_NPPES_NPI_SRC_OTHER_ID_TB
--------------------------------------------------------

  CREATE TABLE "P_NPPES_NPI_SRC_OTHER_ID_TB" ("P_NPI_NUM" VARCHAR2(10), "P_NPPES_NPI_SRC_OTH_ID_SEQ_NUM" NUMBER(5,0), "P_NPPES_NPI_OTHER_PROV_ID" VARCHAR2(20), "P_OTHER_PTY_CD" VARCHAR2(2), "P_OTHER_PROV_ID_STATE_CD" VARCHAR2(2), "P_OTHER_PROV_ID_ISSR_TEXT" VARCHAR2(80), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
