--------------------------------------------------------
--  DDL for Table P_NPPES_NPI_SRC_TXNMY_TB
--------------------------------------------------------

  CREATE TABLE "P_NPPES_NPI_SRC_TXNMY_TB" ("P_NPI_NUM" VARCHAR2(10), "P_NPPES_NPI_SRC_TXNMY_SEQ_NUM" NUMBER(5,0), "P_TXNMY_CD" VARCHAR2(10), "P_LIC_NUM" VARCHAR2(20), "P_LIC_NUM_STATE_CD" VARCHAR2(2), "P_TXNMY_SWITCH_CD" VARCHAR2(1), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
