--------------------------------------------------------
--  DDL for Table P_OWNRSHP_CHG_REQ_TN
--------------------------------------------------------

  CREATE TABLE "P_OWNRSHP_CHG_REQ_TN" ("P_SYS_ID" NUMBER(10,0), "P_OWNRSHP_CHG_EFF_DT" DATE, "P_BUSN_NAM" VARCHAR2(60), "P_OWNRSHP_TY_CD" VARCHAR2(30), "P_FED_TAX_ID" VARCHAR2(9), "B_BUSN_CONTCT_TEXT" VARCHAR2(30), "P_FIRST_NAM" VARCHAR2(25), "P_LAST_NAM" VARCHAR2(35), "P_MI_NAM" VARCHAR2(1), "P_SSN_NUM" VARCHAR2(9), "P_BIRTH_DT" DATE, "P_ENROLLING_PROV_REL_TEXT" VARCHAR2(30), "P_MCARE_ID" VARCHAR2(12), "P_NPI_NUM" VARCHAR2(10), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0)
