--------------------------------------------------------
--  DDL for Table P_PBM_NW_PRTCPTN_TB
--------------------------------------------------------

  CREATE TABLE "P_PBM_NW_PRTCPTN_TB" ("P_SYS_ID" NUMBER(10,0), "P_NW_PART_SK" NUMBER(10,0), "P_PBM_NW_SEQ_NUM" NUMBER(5,0), "P_NW_BEG_DT" DATE, "P_PBM_NW_BEG_DT" DATE, "P_PBM_NW_END_DT" DATE, "P_BRAND_DISCT_PCT" NUMBER(7,2), "P_GNRC_DISCT_PCT" NUMBER(7,2), "P_PRIM_DSPNSNG_TY_CD" VARCHAR2(2), "P_DSPNSNG_FEE_AMT" NUMBER(9,2), "P_PRCS_FEE_AMT" NUMBER(7,2), "P_PRC_LVL_ID" VARCHAR2(2), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
