--------------------------------------------------------
--  DDL for Table P_QSP_QSTNR_TN
--------------------------------------------------------

  CREATE TABLE "P_QSP_QSTNR_TN" ("P_SYS_ID" NUMBER(10,0), "P_QSTNR_SECT_CD" VARCHAR2(5), "P_QSTNR_SEQ_NUM" NUMBER(5,0), "P_QSTNR_RESPONCE_IND" VARCHAR2(1), "P_QSTNR_RESP_TEXT" VARCHAR2(4000), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
