--------------------------------------------------------
--  DDL for Table P_QSP_PROV_RECIP_TN
--------------------------------------------------------

  CREATE TABLE "P_QSP_PROV_RECIP_TN" ("P_QSP_PROV_RECIP_SEQ_NUM" NUMBER(5,0), "P_RECIP_FIRST_NAM" VARCHAR2(25), "P_RECIP_LAST_NAM" VARCHAR2(35), "P_RECIP_REL_CD" VARCHAR2(3), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30), "P_SYS_ID" NUMBER(10,0))
