--------------------------------------------------------
--  DDL for Table P_RA_MEDM_TX
--------------------------------------------------------

  CREATE TABLE "P_RA_MEDM_TX" ("P_SYS_ID" NUMBER(10,0), "P_RA_MEDM_SK" NUMBER(10,0), "P_ERA_ACCT_NUM_LNKG_DESC" VARCHAR2(50), "P_ERA_MTHD_RTRVL_TEXT" VARCHAR2(50), "P_ERA_SUBM_DT" DATE, "P_ERA_REQD_EFF_DT" DATE, "P_CLRG_HOUSE_NAM" VARCHAR2(30), "P_CLRG_HOUSE_CONTCT_NAM" VARCHAR2(30), "G_CLRG_HOUSE_PHONE_SK" NUMBER(10,0), "G_CLRG_HOUSE_EMAIL_SK" NUMBER(10,0), "P_ERA_ASGN_AUTHRTY_TEXT" VARCHAR2(64), "P_ERA_SUBM_RSN_DESC" VARCHAR2(18), "P_ERA_AUTH_SIGN_DESC" VARCHAR2(50), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
