--------------------------------------------------------
--  DDL for Table P_REVAL_STAT_TN
--------------------------------------------------------

  CREATE TABLE "P_REVAL_STAT_TN" ("P_SYS_ID" NUMBER(10,0), "P_REVAL_STARTED_IND" VARCHAR2(1), "P_GENERAL_INFO_STAT_IND" VARCHAR2(1), "P_NAME_ADDR_STAT_IND" VARCHAR2(1), "P_LIC_SPEC_STAT_IND" VARCHAR2(1), "P_FINANCIAL_STAT_IND" VARCHAR2(1), "P_SANCTIONS_STAT_IND" VARCHAR2(1), "P_BANKRUPTCY_STAT_IND" VARCHAR2(1), "P_OWNERSHIP_STAT_IND" VARCHAR2(1), "P_MANAGING_STAT_IND" VARCHAR2(1), "P_REVAL_STAT_CD" VARCHAR2(2), "P_REVAL_STAT_LAST_DT" DATE, "P_REVAL_COMP_DT" DATE, "P_REVAL_COMP_BY_NAM" VARCHAR2(30), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
