--------------------------------------------------------
--  DDL for Table P_RPT_PBM_STATS_TB
--------------------------------------------------------

  CREATE TABLE "P_RPT_PBM_STATS_TB" ("P_RPT_PBM_STATS_SK" NUMBER(10,0), "P_PBM_STATS_RPT_FILE_TY_CD" VARCHAR2(3), "P_FILE_NAM" VARCHAR2(128), "P_FILE_CREATE_DT" DATE, "P_FILE_SIZE_NUM" NUMBER(10,0), "P_PBM_CLNT_ID" VARCHAR2(10), "P_PBM_CONTCT_NAM" VARCHAR2(50), "P_PBM_CONTCT_PHONE_NUM" VARCHAR2(10), "P_PBM_CONTCT_PHONE_EXT_NUM" VARCHAR2(6), "P_INACT_REC_CNT" NUMBER(10,0), "P_ACTV_REC_CNT" NUMBER(10,0), "P_TOT_REC_SENT_CNT" NUMBER(10,0), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "P_TOT_UNQ_ID_CNT" NUMBER(10,0), "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
