--------------------------------------------------------
--  DDL for Table P_RPT_LN_SN_ERR_TB
--------------------------------------------------------

  CREATE TABLE "P_RPT_LN_SN_ERR_TB" ("P_RPT_LN_SN_ERR_SK" NUMBER(10,0), "P_SN_PROV_ID" VARCHAR2(15), "P_SN_NAM" VARCHAR2(60), "P_SN_SANC_DT" DATE, "P_SN_SANC_STATE" VARCHAR2(2), "P_SN_SANC_LIC_NUM" VARCHAR2(12), "P_SN_SANC_RSN" VARCHAR2(250), "P_SN_SANC_TERMS" VARCHAR2(200), "P_SN_SANC_FRAUD_IND" VARCHAR2(1), "P_SN_SANC_LIC_LOSS_IND" VARCHAR2(1), "P_SN_ERROR_MSG" VARCHAR2(40), "P_SN_PRCS_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
