--------------------------------------------------------
--  DDL for Table P_RPT_PHARM_UPD_TB
--------------------------------------------------------

  CREATE TABLE "P_RPT_PHARM_UPD_TB" ("P_RPT_PHARM_UPD_SK" NUMBER(10,0), "P_SYS_ID" NUMBER(10,0), "R_IMAGE_CD" VARCHAR2(1), "P_ALT_ID" VARCHAR2(15), "P_DEA_ID" VARCHAR2(15), "P_FED_TAX_ID" VARCHAR2(15), "P_NPI_NUM" VARCHAR2(15), "P_NCPDP_ID" VARCHAR2(15), "P_SORT_NAM" VARCHAR2(60), "P_ENROL_STAT_BEG_DT" DATE, "P_ENROL_STAT_END_DT" DATE, "P_LIC_CERT_NUM" VARCHAR2(10), "G_LINE1_ADR" VARCHAR2(64), "G_LINE2_ADR" VARCHAR2(64), "G_CITY_NAM" VARCHAR2(30), "G_US_STATE_CD" VARCHAR2(2), "G_ZIP5_CD" VARCHAR2(5), "G_ZIP4_CD" VARCHAR2(4), "G_PHONE_NUM" VARCHAR2(10), "G_FAX_NUM" VARCHAR2(10), "G_ADR_USG_TY_CD" VARCHAR2(2), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
