--------------------------------------------------------
--  DDL for Table P_RPT_LN_CL_ERR_TB
--------------------------------------------------------

  CREATE TABLE "P_RPT_LN_CL_ERR_TB" ("P_RPT_LN_CL_ERR_SK" NUMBER(10,0), "P_CL_PROV_ID" VARCHAR2(15), "P_CL_NAME" VARCHAR2(60), "P_CL_CLIA_NUM" VARCHAR2(20), "P_CL_EXP_DT" DATE, "P_CL_LAB_TYPE" VARCHAR2(50), "P_CL_TERM_CD" VARCHAR2(3), "P_CL_TERM_RSN" VARCHAR2(100), "P_CL_EXPIRED_CD" VARCHAR2(3), "P_CL_ERROR_MSG" VARCHAR2(40), "P_CL_PRCS_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
