--------------------------------------------------------
--  DDL for Table P_RPT_LN_ML_ERR_TB
--------------------------------------------------------

  CREATE TABLE "P_RPT_LN_ML_ERR_TB" ("P_RPT_LN_ML_ERR_SK" NUMBER(10,0), "P_ML_PROV_ID" VARCHAR2(15), "P_ML_NAM" VARCHAR2(60), "P_ML_LIC_NUM" VARCHAR2(20), "P_ML_STATE" VARCHAR2(10), "P_ML_LIC_EFF_DT" DATE, "P_ML_LIC_EXP_DT" DATE, "P_ML_LIC_STAT" VARCHAR2(10), "P_ML_TAXID" VARCHAR2(12), "P_ML_DOB" DATE, "P_ML_ERROR_MSG" VARCHAR2(40), "P_ML_PRCS_DT" DATE, "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
