--------------------------------------------------------
--  DDL for Table P_TRNG_SESSN_ATTACH_TB
--------------------------------------------------------

  CREATE TABLE "P_TRNG_SESSN_ATTACH_TB" ("P_TRNG_CRSE_ID" VARCHAR2(10), "P_TRNG_SESSN_ID" VARCHAR2(10), "G_ATTACH_SK" NUMBER(10,0), "G_DTCHD_ATTACH_IND" VARCHAR2(1) DEFAULT 'N', "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
