--------------------------------------------------------
--  DDL for Table P_TRNG_SESSN_TB
--------------------------------------------------------

  CREATE TABLE "P_TRNG_SESSN_TB" ("P_TRNG_CRSE_ID" VARCHAR2(10), "P_TRNG_SESSN_ID" VARCHAR2(10), "P_TRNG_SESSN_DT" DATE, "P_TRNG_SESSN_DESC" VARCHAR2(80), "P_TRNG_SESSN_RGN_CD" VARCHAR2(1), "P_TRNG_SESSN_TM_FRM_TEXT" VARCHAR2(20), "P_TRNG_SESSN_LOCN_TEXT" VARCHAR2(80), "P_TRNG_SESSN_MAX_ENROL_NUM" NUMBER(10,0), "P_TRNG_SESSN_EVAL_RECD_NUM" NUMBER(10,0), "P_TRNG_SESSN_STAT_CD" VARCHAR2(1), "P_TRNG_SESSN_INSTRCR_NAM" VARCHAR2(50), "G_NOTE_SET_SK" NUMBER(10,0), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE)
