--------------------------------------------------------
--  DDL for Table P_TY_SPECL_TXNMY_XREF_TB
--------------------------------------------------------

  CREATE TABLE "P_TY_SPECL_TXNMY_XREF_TB" ("P_INDIV_GRP_CD" VARCHAR2(1), "P_TY_CD" VARCHAR2(3), "P_SPECL_CD" VARCHAR2(3), "P_TXNMY_CD" VARCHAR2(10), "L_HIBERNATE_VER_NUM" NUMBER(9,0) DEFAULT 0, "G_AUD_ADD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_ADD_USER_ID" VARCHAR2(30), "G_AUD_TS" TIMESTAMP (6) DEFAULT SYSDATE, "G_AUD_USER_ID" VARCHAR2(30))
