-- ============================================================
-- Migration Metadata Repository
-- Oracle -> PostgreSQL Converter
-- Generated from PK/FK Excel
-- ============================================================

DROP TABLE IF EXISTS migration_primary_keys;
DROP TABLE IF EXISTS migration_foreign_keys;

CREATE TABLE migration_primary_keys (
    module_name       VARCHAR(100) NOT NULL,
    table_name        VARCHAR(128) NOT NULL,
    column_name       VARCHAR(128) NOT NULL,
    constraint_name   VARCHAR(128) NOT NULL
);

CREATE TABLE migration_foreign_keys (
    module_name       VARCHAR(100) NOT NULL,
    child_table       VARCHAR(128) NOT NULL,
    child_column      VARCHAR(128) NOT NULL,
    parent_table      VARCHAR(128) NOT NULL,
    parent_column     VARCHAR(128) NOT NULL,
    fk_name           VARCHAR(128),
    pk_name           VARCHAR(128),
    position_no       INTEGER
);

CREATE INDEX idx_pk_table ON migration_primary_keys(table_name);
CREATE INDEX idx_fk_child ON migration_foreign_keys(child_table);
CREATE INDEX idx_fk_parent ON migration_foreign_keys(parent_table);

-- 209 Primary Key INSERTs

INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ACPTNC_TB', 'P_SYS_ID', 'P_ACPTNC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ACPTNC_TB', 'P_ACPTNC_SK', 'P_ACPTNC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_AFFL_TB', 'P_GRP_SYS_ID', 'P_AFFL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_AFFL_TB', 'P_MBR_SYS_ID', 'P_AFFL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_AFFL_TB', 'P_AFFL_SK', 'P_AFFL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_AFFL_TX', 'P_GRP_SYS_ID', 'P_AFFL_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_AFFL_TX', 'P_MBR_SYS_ID', 'P_AFFL_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_AFFL_TX', 'P_AFFL_SK', 'P_AFFL_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ALT_ID_TB', 'P_SYS_ID', 'P_ALT_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ALT_ID_TB', 'P_ALT_ID_SK', 'P_ALT_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_APPL_STAT_TB', 'P_SYS_ID', 'P_APPL_STAT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_APPL_STAT_TB', 'P_APPL_STAT_SK', 'P_APPL_STAT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_BLNG_MEDM_TB', 'P_SYS_ID', 'P_BLNG_MEDM_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_BLNG_MEDM_TB', 'P_BLNG_MEDM_SK', 'P_BLNG_MEDM_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CARE_CRD_TX', 'P_SYS_ID', 'P_CARE_CRD_TX_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CARE_CRD_TX', 'P_CARE_CRD_SK', 'P_CARE_CRD_TX_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_CERT_TB', 'P_CLIA_NUM', 'P_CLIA_CERT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_CERT_TB', 'P_CLIA_CERT_LI_NUM', 'P_CLIA_CERT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_CERT_TB', 'P_CLIA_CERT_TY_CD', 'P_CLIA_CERT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_CERT_TB', 'P_CLIA_CERT_SEQ_NUM', 'P_CLIA_CERT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_LAB_CD_TB', 'P_CLIA_NUM', 'P_CLIA_LAB_CD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_LAB_CD_TB', 'P_CLIA_LAB_CD', 'P_CLIA_LAB_CD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_LAB_CD_TB', 'P_CLIA_CERT_BEG_DT', 'P_CLIA_LAB_CD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_LAB_TB', 'P_CLIA_NUM', 'P_CLIA_LAB_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_PROV_TB', 'P_SYS_ID', 'P_CLIA_PROV_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CLIA_PROV_TB', 'P_CLIA_PROV_SK', 'P_CLIA_PROV_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CMN_LIC_UPLOAD_TB', 'P_LIC_CERT_NUM', 'P_CMN_LIC_UPLOAD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_CMN_LIC_UPLOAD_TB', 'P_CMN_LIC_ACTN_CD', 'P_CMN_LIC_UPLOAD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_COS_STAT_TB', 'P_SYS_ID', 'P_COS_STAT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_COS_STAT_TB', 'P_COS_STAT_SK', 'P_COS_STAT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_DSH_TB', 'P_SYS_ID', 'P_DSH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_DSH_TB', 'P_DSH_SK', 'P_DSH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_DSH_TX', 'P_SYS_ID', 'P_DSH_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_DSH_TX', 'P_DSH_SK', 'P_DSH_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_DTL_TB', 'P_SYS_ID', 'P_DTL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_DTL_TX', 'P_SYS_ID', 'P_DTL_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ELIGIBLE_RECIP_ENTRY_FORM_TN', 'P_SYS_ID', 'P_ELIGIBLE_RECIP_ENTRY_FORM_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ELIGIBLE_RECIP_ENTRY_FORM_TN', 'P_RECIP_SEQ_NUM', 'P_ELIGIBLE_RECIP_ENTRY_FORM_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_AFFL_TB', 'P_ENROL_SYS_ID', 'P_ENROL_AFFL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_AFFL_TB', 'P_ENROL_AFFL_SEQ_NUM', 'P_ENROL_AFFL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_AFFL_TX', 'P_ENROL_SYS_ID', 'P_ENROL_AFFL_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_AFFL_TX', 'P_ENROL_AFFL_SEQ_NUM', 'P_ENROL_AFFL_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_ALT_ID_TB', 'P_SYS_ID', 'P_ENROL_ALT_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_ALT_ID_TB', 'P_ENROL_ALT_ID_SEQ_NUM', 'P_ENROL_ALT_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_STAT_TB', 'P_SYS_ID', 'P_ENROL_STAT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_STAT_TB', 'P_ENROL_STAT_SK', 'P_ENROL_STAT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_STAT_TX', 'P_SYS_ID', 'P_ENROL_STAT_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_STAT_TX', 'P_ENROL_STAT_SK', 'P_ENROL_STAT_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_TP_INFO_TB', 'P_SYS_ID', 'P_ENROL_TP_INFO_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_TP_TXN_INFO_TB', 'P_SYS_ID', 'P_ENROL_TP_TXN_INFO_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_ENROL_TP_TXN_INFO_TB', 'P_TXN_TP_INFO_SK', 'P_ENROL_TP_TXN_INFO_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_EVENT_RSN_TB', 'P_SYS_ID', 'P_EVENT_RSN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_EVENT_RSN_TB', 'P_EVENT_SK', 'P_EVENT_RSN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_EVENT_RSN_TB', 'P_EVENT_RSN_SK', 'P_EVENT_RSN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_EVENT_TB', 'P_SYS_ID', 'P_EVENT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_EVENT_TB', 'P_EVENT_SK', 'P_EVENT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_FACI_TB', 'P_SYS_ID', 'P_FACI_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_FACI_TB', 'P_FACI_SK', 'P_FACI_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_GLBL_ENDRSMNTS_SOUGHT_TN', 'P_SYS_ID', 'P_GLBL_ENDRSMNTS_SOUGHT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_GLBL_ENDRSMNTS_SOUGHT_TN', 'P_ENDRSMNT_CD', 'P_GLBL_ENDRSMNTS_SOUGHT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_GLBL_ENDRSMNTS_TN', 'P_SYS_ID', 'P_GLBL_ENDRSMNTS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_GLBL_ENDRSMNTS_TN', 'P_ENDRSMNT_CD', 'P_GLBL_ENDRSMNTS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_ALT_ID_TB', 'P_HCIDEA_ALT_ID', 'P_HCIDEA_ALT_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_ALT_ID_TB', 'P_HCIDEA_ALT_ID_TY_CD', 'P_HCIDEA_ALT_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_ALT_ID_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_ALT_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_MCAID_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_MCAID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_MCAID_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_MCAID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_MCAID_TB', 'P_HCIDEA_MCAID_STATE_CD', 'P_HCIDEA_PROV_ADR_MCAID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_MCAID_TB', 'P_HCIDEA_MCAID_ID', 'P_HCIDEA_PROV_ADR_MCAID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_PHONE_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_PHONE_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_PHONE_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_PHONE_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_PHONE_TB', 'P_HCIDEA_PHONE_SEQ_NUM', 'P_HCIDEA_PROV_ADR_PHONE_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_SPI_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_SPI_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_SPI_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_SPI_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_SPI_TB', 'P_HCIDEA_SPI_ROOT_ID', 'P_HCIDEA_PROV_ADR_SPI_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_SPI_TB', 'P_HCIDEA_SPI_LOCN_CD', 'P_HCIDEA_PROV_ADR_SPI_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_DEG_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_DEG_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_DEG_TB', 'P_HCIDEA_DEG_SEQ_NUM', 'P_HCIDEA_PROV_DEG_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_LIC_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_LIC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_LIC_TB', 'P_HCIDEA_LIC_SEQ_NUM', 'P_HCIDEA_PROV_LIC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_SPECL_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_SPECL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_SPECL_TB', 'P_HCIDEA_SPECL_SEQ_NUM', 'P_HCIDEA_PROV_SPECL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_TXNMY_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TXNMY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_HCIDEA_PROV_TXNMY_TB', 'P_HCIDEA_TXNMY_SEQ_NUM', 'P_HCIDEA_PROV_TXNMY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_IF_1915I_TB', 'P_IF_1915I_SK', 'P_IF_1915I_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_IF_PT_PS_TB', 'P_IF_NAM', 'P_IF_PT_PS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_IF_PT_PS_TB', 'P_TY_CD', 'P_IF_PT_PS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_IF_PT_PS_TB', 'P_SPECL_CD', 'P_IF_PT_PS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_IF_SANDATA_TB', 'P_IF_SANDATA_SK', 'P_IF_SANDATA_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_IF_THERAP_TB', 'P_IF_THERAP_SK', 'P_IF_THERAP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_INTERP_SVC_TB', 'P_SYS_ID', 'P_INTERP_SVC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_INTERP_SVC_TB', 'P_INTERP_SVC_SK', 'P_INTERP_SVC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_LANG_TB', 'P_SYS_ID', 'P_LANG_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_LANG_TB', 'P_LANG_SK', 'P_LANG_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_LIC_CERT_TB', 'P_SYS_ID', 'P_LIC_CERT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_LIC_CERT_TB', 'P_LIC_CERT_SK', 'P_LIC_CERT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_LTR_REQ_TB', 'P_SYS_ID', 'P_LTR_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_LTR_REQ_TB', 'G_COTS_LTR_REQ_SK', 'P_LTR_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_MCARE_TB', 'P_SYS_ID', 'P_MCARE_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_MCARE_TB', 'P_MCARE_SK', 'P_MCARE_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_MC_PRTCPTN_TN', 'P_SYS_ID', 'P_MC_PRTCPTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_MC_PRTCPTN_TN', 'P_MC_PRTCPTN_PROG_CD', 'P_MC_PRTCPTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_MC_PRTCPTN_TN', 'P_MC_PROG_PRTCPTN_BEG_DT', 'P_MC_PRTCPTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NONMED_PROV_RECIP_TN', 'P_SYS_ID', 'P_NONMED_PROV_RECIP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NONMED_PROV_RECIP_TN', 'B_SYS_ID', 'P_NONMED_PROV_RECIP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NONMED_PROV_RECIP_TN', 'G_CNTY_CD', 'P_NONMED_PROV_RECIP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NONMED_PROV_RECIP_TN', 'P_SCRN_LOCN_CD', 'P_NONMED_PROV_RECIP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NPPES_NPI_SRC_OTHER_ID_TB', 'P_NPI_NUM', 'P_NPPES_NPI_SRC_OTHER_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NPPES_NPI_SRC_OTHER_ID_TB', 'P_NPPES_NPI_SRC_OTH_ID_SEQ_NUM', 'P_NPPES_NPI_SRC_OTHER_ID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NPPES_NPI_SRC_TB', 'P_NPI_NUM', 'P_NPPES_NPI_SRC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NPPES_NPI_SRC_TXNMY_TB', 'P_NPI_NUM', 'P_NPPES_NPI_SRC_TXNMY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NPPES_NPI_SRC_TXNMY_TB', 'P_NPPES_NPI_SRC_TXNMY_SEQ_NUM', 'P_NPPES_NPI_SRC_TXNMY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NUM_BED_TB', 'P_SYS_ID', 'P_NUM_BED_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NUM_BED_TB', 'P_NUM_BED_SK', 'P_NUM_BED_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NW_PART_TB', 'P_SYS_ID', 'P_NW_PART_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_NW_PART_TB', 'P_NW_PART_SK', 'P_NW_PART_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OFC_HRS_TB', 'P_SYS_ID', 'P_OFC_HRS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OFC_HRS_TB', 'P_OFC_HRS_SK', 'P_OFC_HRS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OIG_PROV_MATCH_TB', 'P_SYS_ID', 'P_OIG_PROV_MATCH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OIG_PROV_MATCH_TB', 'P_OIG_SK', 'P_OIG_PROV_MATCH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OIG_PROV_MATCH_TB', 'P_OIG_MATCH_CD', 'P_OIG_PROV_MATCH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OIG_PROV_XREF_TB', 'P_SYS_ID', 'P_OIG_PROV_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OIG_PROV_XREF_TB', 'P_OIG_SK', 'P_OIG_PROV_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OIG_TB', 'P_OIG_SK', 'P_OIG_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OWNER_DTL_TB', 'P_OWNER_TAX_ID', 'P_OWNER_DTL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OWNER_DTL_TB', 'P_OWNER_DTL_SEQ_NUM', 'P_OWNER_DTL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OWNER_XREF_TB', 'P_SYS_ID', 'P_OWNER_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OWNER_XREF_TB', 'P_OWNER_TAX_ID', 'P_OWNER_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OWNER_XREF_TB', 'P_OWNER_DTL_SEQ_NUM', 'P_OWNER_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OWNER_XREF_TB', 'P_OWNER_XREF_SK', 'P_OWNER_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_OWNRSHP_CHG_REQ_TN', 'P_SYS_ID', 'P_OWNRSHP_CHG_REQ_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PBM_NW_PRTCPTN_TB', 'P_SYS_ID', 'P_PBM_NW_PRTCPTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PBM_NW_PRTCPTN_TB', 'P_NW_PART_SK', 'P_PBM_NW_PRTCPTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PBM_NW_PRTCPTN_TB', 'P_PBM_NW_SEQ_NUM', 'P_PBM_NW_PRTCPTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PREV_MCAID_TB', 'P_SYS_ID', 'P_PREV_MCAID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PREV_MCAID_TB', 'P_PREV_MCAID_SK', 'P_PREV_MCAID_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PREV_NAM_TN', 'P_SYS_ID', 'P_PREV_NAM_TN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PREV_NAM_TN', 'P_PREV_NAM_SEQ_NUM', 'P_PREV_NAM_TN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PROG_INFO_REQ_TB', 'P_SYS_ID', 'P_PROG_INFO_REQ_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PROG_INFO_REQ_TB', 'P_PROG_INFO_REQ_SK', 'P_PROG_INFO_REQ_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PROV_CNTY_TN', 'P_SYS_ID', 'P_PROV_CNTY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PROV_CNTY_TN', 'G_CNTY_CD', 'P_PROV_CNTY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PROV_CNTY_TN', 'P_SCRN_LOCN_CD', 'P_PROV_CNTY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_PROV_HRARCHY_TB', 'P_PROV_HRARCHY_NUM', 'P_PROV_HRARCHY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_PROV_RECIP_TN', 'P_SYS_ID', 'P_QSP_PROV_RECIP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_PROV_RECIP_TN', 'P_QSP_PROV_RECIP_SEQ_NUM', 'P_QSP_PROV_RECIP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_QSTNR_INITIALED_RESP_TN', 'P_SYS_ID', 'P_QSP_QSTNR_INITIALED_RESP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_QSTNR_INITIALED_RESP_TN', 'P_QSTNR_SECT_CD', 'P_QSP_QSTNR_INITIALED_RESP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_QSTNR_INITIALED_RESP_TN', 'P_QSTNR_SEQ_NUM', 'P_QSP_QSTNR_INITIALED_RESP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_QSTNR_TN', 'P_SYS_ID', 'P_QSP_QSTNR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_QSTNR_TN', 'P_QSTNR_SECT_CD', 'P_QSP_QSTNR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSP_QSTNR_TN', 'P_QSTNR_SEQ_NUM', 'P_QSP_QSTNR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_ADVRS_LEGAL_ACTN_TB', 'P_SYS_ID', 'P_QSTNR_ADVRS_LEGAL_ACTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_ADVRS_LEGAL_ACTN_TB', 'P_QSTNR_SEQ_NUM', 'P_QSTNR_ADVRS_LEGAL_ACTN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_EXCLSN_TB', 'P_SYS_ID', 'P_QSTNR_EXCLSN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_EXCLSN_TB', 'P_QSTNR_SEQ_NUM', 'P_QSTNR_EXCLSN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_OTHER_STATE_TB', 'P_SYS_ID', 'P_QSTNR_OTHER_STATE_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_OVR_PMT_TB', 'P_SYS_ID', 'P_QSTNR_OVR_PMT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_OVR_PMT_TB', 'P_QSTNR_SEQ_NUM', 'P_QSTNR_OVR_PMT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_TB', 'P_SYS_ID', 'P_QSTNR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_QSTNR_TB', 'P_QSTNR_SK', 'P_QSTNR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RA_MEDM_TB', 'P_SYS_ID', 'P_RA_MEDM_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RA_MEDM_TB', 'P_RA_MEDM_SK', 'P_RA_MEDM_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RA_MEDM_TX', 'P_SYS_ID', 'P_RA_MEDM_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RA_MEDM_TX', 'P_RA_MEDM_SK', 'P_RA_MEDM_PX');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_REQ_ATTACH_TB', 'P_SYS_ID', 'P_REQ_ATTACH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_REQ_ATTACH_TB', 'P_REQ_ATTACH_SK', 'P_REQ_ATTACH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_REVAL_STAT_TN', 'P_SYS_ID', 'P_REVAL_STAT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_CLDI_ERR_TB', 'P_CLDI_ERR_SK', 'P_RPT_CLDI_ERR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_CMS_UPD_TB', 'P_RPT_CMS_UPD_SK', 'P_RPT_CMS_UPD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_DOT_EXTRT_TN', 'P_RPT_DOT_EXTRT_SK', 'P_RPT_DOT_EXTRT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_NCPDP_IFACE_ERR_TB', 'P_NCPDP_IFACE_ERR_SK', 'P_RPT_NCPDP_IFACE_ERR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_NCPDP_IFACE_UPD_TB', 'P_NCPDP_IFACE_UPD_SK', 'P_RPT_NCPDP_IFACE_UPD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_NCPDP_TB', 'P_RPT_NCPDP_SK', 'P_RPT_NCPDP_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_PBM_STATS_TB', 'P_RPT_PBM_STATS_SK', 'P_RPT_PBM_STATS_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_PHARM_UPD_TB', 'P_RPT_PHARM_UPD_SK', 'P_RPT_PHARM_UPD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RPT_TERM_LCKN_LCKT_TB', 'P_RPT_TERM_LCKN_LCKT_SK', 'P_RPT_TERM_LCKN_LCKT_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RSK_SCRN_TN', 'P_SYS_ID', 'P_RSK_SCRN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_RSK_SCRN_TN', 'P_RSK_SCRN_SK', 'P_RSK_SCRN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_SPECL_NEED_TB', 'P_SYS_ID', 'P_SPECIAL_NEED_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_SPECL_NEED_TB', 'P_SPECL_NEED_SK', 'P_SPECIAL_NEED_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_SPECL_TB', 'P_SYS_ID', 'P_SPECL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_SPECL_TB', 'P_SPECL_SK', 'P_SPECL_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_SVC_TY_CD_TB', 'P_SYS_ID', 'P_SVC_TY_CD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_SVC_TY_CD_TB', 'P_SVC_TY_SK', 'P_SVC_TY_CD_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TAX_NTC_TB', 'P_SYS_ID', 'P_TAX_NTC_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_CRSE_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_CRSE_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_RGSTR_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_RGSTR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_RGSTR_TB', 'P_TRNG_SESSN_ID', 'P_TRNG_RGSTR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_RGSTR_TB', 'G_PROV_CMN_ENTY_SK', 'P_TRNG_RGSTR_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_SESSN_ATTACH_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_SESSN_ATTACH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_SESSN_ATTACH_TB', 'P_TRNG_SESSN_ID', 'P_TRNG_SESSN_ATTACH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_SESSN_ATTACH_TB', 'G_ATTACH_SK', 'P_TRNG_SESSN_ATTACH_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_SESSN_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_SESSN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TRNG_SESSN_TB', 'P_TRNG_SESSN_ID', 'P_TRNG_SESSN_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TXNMY_TB', 'P_SYS_ID', 'P_TXNMY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TXNMY_TB', 'P_TXNMY_SK', 'P_TXNMY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_SPECL_TXNMY_XREF_TB', 'P_INDIV_GRP_CD', 'P_TY_SPECL_TXNMY_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_SPECL_TXNMY_XREF_TB', 'P_TY_CD', 'P_TY_SPECL_TXNMY_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_SPECL_TXNMY_XREF_TB', 'P_SPECL_CD', 'P_TY_SPECL_TXNMY_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_SPECL_TXNMY_XREF_TB', 'P_TXNMY_CD', 'P_TY_SPECL_TXNMY_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_SPECL_XREF_TB', 'P_TY_CD', 'P_TY_SPECL_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_SPECL_XREF_TB', 'P_SPECL_CD', 'P_TY_SPECL_XREF_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_TB', 'P_SYS_ID', 'P_TY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_TY_TB', 'P_TY_SK', 'P_TY_PK');
INSERT INTO migration_primary_keys (module_name, table_name, column_name, constraint_name) VALUES ('Provider', 'P_WEB_DSPLY_TB', 'P_SYS_ID', 'P_WEB_DSPLY_PK');

-- 120 Foreign Key INSERTs

INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ACPTNC_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ACPTNC_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_AFFL_TB', 'P_GRP_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_AFFL_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_AFFL_TB', 'P_MBR_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_AFFL_F2', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_AFFL_TX', 'P_GRP_SYS_ID', 'P_AFFL_TB', 'P_GRP_SYS_ID', 'P_AFFL_FX1', 'P_AFFL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_AFFL_TX', 'P_MBR_SYS_ID', 'P_AFFL_TB', 'P_MBR_SYS_ID', 'P_AFFL_FX1', 'P_AFFL_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_AFFL_TX', 'P_AFFL_SK', 'P_AFFL_TB', 'P_AFFL_SK', 'P_AFFL_FX1', 'P_AFFL_PK', 3);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ALT_ID_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ALT_ID_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_APPL_STAT_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_APPL_STAT_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_BLNG_MEDM_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_BLNG_MEDM_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_CARE_CRD_TX', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_CARE_CRD_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_CLIA_CERT_TB', 'P_CLIA_NUM', 'P_CLIA_LAB_TB', 'P_CLIA_NUM', 'P_CLIA_CERT_F1', 'P_CLIA_LAB_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_CLIA_LAB_CD_TB', 'P_CLIA_NUM', 'P_CLIA_LAB_TB', 'P_CLIA_NUM', 'P_CLIA_LAB_CD_F1', 'P_CLIA_LAB_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_CLIA_LAB_TB', 'G_NOTE_SET_SK', 'G_NOTE_SET_TB', 'G_NOTE_SET_SK', 'P_CLIA_LAB_F1', 'G_NOTE_SET_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_CLIA_LAB_TB', 'G_CMN_ENTY_SK', 'G_CMN_ENTY_TB', 'G_CMN_ENTY_SK', 'P_CLIA_LAB_F2', 'G_CMN_ENTY_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_CLIA_PROV_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_CLIA_PROV_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_CLIA_PROV_TB', 'P_CLIA_NUM', 'P_CLIA_LAB_TB', 'P_CLIA_NUM', 'P_CLIA_PROV_F2', 'P_CLIA_LAB_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_COS_STAT_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_COS_STAT_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_DSH_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_DSH_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_DSH_TX', 'P_SYS_ID', 'P_DSH_TB', 'P_SYS_ID', 'P_DSH_FX1', 'P_DSH_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_DSH_TX', 'P_DSH_SK', 'P_DSH_TB', 'P_DSH_SK', 'P_DSH_FX1', 'P_DSH_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_DTL_TB', 'G_NOTE_SET_SK', 'G_NOTE_SET_TB', 'G_NOTE_SET_SK', 'P_DTL_F1', 'G_NOTE_SET_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_DTL_TB', 'G_CMN_ENTY_SK', 'G_CMN_ENTY_TB', 'G_CMN_ENTY_SK', 'P_DTL_F2', 'G_CMN_ENTY_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_DTL_TX', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_DTL_FX1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ELIGIBLE_RECIP_ENTRY_FORM_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ELIGIBLE_RECIP_ENTRY_FORMFN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_AFFL_TB', 'P_MBR_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ENROL_AFFL_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_AFFL_TB', 'P_GRP_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ENROL_AFFL_F2', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_AFFL_TB', 'P_ENROL_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ENROL_AFFL_F3', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_AFFL_TX', 'P_ENROL_SYS_ID', 'P_ENROL_AFFL_TB', 'P_ENROL_SYS_ID', 'P_ENROL_AFFL_FX1', 'P_ENROL_AFFL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_AFFL_TX', 'P_ENROL_AFFL_SEQ_NUM', 'P_ENROL_AFFL_TB', 'P_ENROL_AFFL_SEQ_NUM', 'P_ENROL_AFFL_FX1', 'P_ENROL_AFFL_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_ALT_ID_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ENROL_ALT_ID_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_STAT_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ENROL_STAT_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_STAT_TX', 'P_SYS_ID', 'P_ENROL_STAT_TB', 'P_SYS_ID', 'P_ENROL_STAT_FX1', 'P_ENROL_STAT_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_STAT_TX', 'P_ENROL_STAT_SK', 'P_ENROL_STAT_TB', 'P_ENROL_STAT_SK', 'P_ENROL_STAT_FX1', 'P_ENROL_STAT_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_TP_INFO_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ENROL_TP_INFO_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_TP_INFO_TB', 'G_NOTE_SET_SK', 'G_NOTE_SET_TB', 'G_NOTE_SET_SK', 'P_ENROL_TP_INFO_F2', 'G_NOTE_SET_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_ENROL_TP_TXN_INFO_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_ENROL_TP_TXN_INFO_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_EVENT_RSN_TB', 'P_SYS_ID', 'P_EVENT_TB', 'P_SYS_ID', 'P_EVENT_RSN_F1', 'P_EVENT_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_EVENT_RSN_TB', 'P_EVENT_SK', 'P_EVENT_TB', 'P_EVENT_SK', 'P_EVENT_RSN_F1', 'P_EVENT_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_EVENT_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_EVENT_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_FACI_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_FACI_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_GLBL_ENDRSMNTS_SOUGHT_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_GLBL_ENDRSMNTS_SOUGHT_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_GLBL_ENDRSMNTS_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_GLBL_ENDRSMNTS_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_ALT_ID_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_ALT_ID_F1', 'P_HCIDEA_PROV_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_MCAID_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_MCAID_F1', 'P_HCIDEA_PROV_ADR_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_MCAID_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_MCAID_F1', 'P_HCIDEA_PROV_ADR_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_PHONE_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADDR_PHONE_F1', 'P_HCIDEA_PROV_ADR_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_PHONE_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADDR_PHONE_F1', 'P_HCIDEA_PROV_ADR_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_SPI_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_SPI_F1', 'P_HCIDEA_PROV_ADR_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_SPI_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_ADR_SYS_ID', 'P_HCIDEA_PROV_ADR_SPI_F1', 'P_HCIDEA_PROV_ADR_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_ADR_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_ADR_F1', 'P_HCIDEA_PROV_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_DEG_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_DEG_F1', 'P_HCIDEA_PROV_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_LIC_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_LIC_F1', 'P_HCIDEA_PROV_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_SPECL_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_SPECL_F1', 'P_HCIDEA_PROV_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_HCIDEA_PROV_TXNMY_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TB', 'P_HCIDEA_SYS_ID', 'P_HCIDEA_PROV_TXNMY_F1', 'P_HCIDEA_PROV_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_INTERP_SVC_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_INTERP_SVC_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_LANG_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_LANG_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_LIC_CERT_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_LIC_CERT_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_LTR_REQ_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_LTR_REQ_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_LTR_REQ_TB', 'G_COTS_LTR_REQ_SK', 'G_COTS_LTR_REQ_TB', 'G_COTS_LTR_REQ_SK', 'P_LTR_REQ_F2', 'G_COTS_LTR_REQ_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_MCARE_TB', 'T_CARR_ID', 'T_CARR_TB', 'T_CARR_ID', 'P_MCARE_F1', 'T_CARR_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_MCARE_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_MCARE_F2', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_MC_PRTCPTN_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_MC_PRTCPTN_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NONMED_PROV_RECIP_TN', 'P_SYS_ID', 'P_PROV_CNTY_TN', 'P_SYS_ID', 'P_NONMED_PROV_RECIP_FN3', 'P_PROV_CNTY_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NONMED_PROV_RECIP_TN', 'G_CNTY_CD', 'P_PROV_CNTY_TN', 'G_CNTY_CD', 'P_NONMED_PROV_RECIP_FN3', 'P_PROV_CNTY_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NONMED_PROV_RECIP_TN', 'P_SCRN_LOCN_CD', 'P_PROV_CNTY_TN', 'P_SCRN_LOCN_CD', 'P_NONMED_PROV_RECIP_FN3', 'P_PROV_CNTY_PK', 3);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NPPES_NPI_SRC_OTHER_ID_TB', 'P_NPI_NUM', 'P_NPPES_NPI_SRC_TB', 'P_NPI_NUM', 'P_NPPES_NPI_SRC_OTHER_ID_F1', 'P_NPPES_NPI_SRC_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NPPES_NPI_SRC_TXNMY_TB', 'P_NPI_NUM', 'P_NPPES_NPI_SRC_TB', 'P_NPI_NUM', 'P_NPPES_NPI_SRC_TXNMY_F1', 'P_NPPES_NPI_SRC_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NUM_BED_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_NUM_BED_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NW_PART_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_NW_PART_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_NW_PART_TB', 'R_NW_ID', 'R_PROV_NW_TB', 'R_NW_ID', 'P_NW_PART_F2', 'R_PROV_NW_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OFC_HRS_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_OFC_HRS_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OIG_PROV_MATCH_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_OIG_PROV_MATCH_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OIG_PROV_MATCH_TB', 'P_SYS_ID', 'P_OIG_PROV_XREF_TB', 'P_SYS_ID', 'P_OIG_PROV_MATCH_F2', 'P_OIG_PROV_XREF_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OIG_PROV_MATCH_TB', 'P_OIG_SK', 'P_OIG_PROV_XREF_TB', 'P_OIG_SK', 'P_OIG_PROV_MATCH_F2', 'P_OIG_PROV_XREF_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OIG_PROV_XREF_TB', 'P_OIG_SK', 'P_OIG_TB', 'P_OIG_SK', 'P_OIG_PROV_XREF_F1', 'P_OIG_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OIG_PROV_XREF_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_OIG_PROV_XREF_F2', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OIG_TB', 'G_CMN_ENTY_SK', 'G_CMN_ENTY_TB', 'G_CMN_ENTY_SK', 'P_OIG_F1', 'G_CMN_ENTY_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OIG_TB', 'G_NOTE_SET_SK', 'G_NOTE_SET_TB', 'G_NOTE_SET_SK', 'P_OIG_F2', 'G_NOTE_SET_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OWNER_XREF_TB', 'P_OWNER_TAX_ID', 'P_OWNER_DTL_TB', 'P_OWNER_TAX_ID', 'P_OWNER_XREF_F1', 'P_OWNER_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OWNER_XREF_TB', 'P_OWNER_DTL_SEQ_NUM', 'P_OWNER_DTL_TB', 'P_OWNER_DTL_SEQ_NUM', 'P_OWNER_XREF_F1', 'P_OWNER_DTL_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OWNER_XREF_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_OWNER_XREF_F2', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_OWNRSHP_CHG_REQ_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_OWNRSHP_CHG_REQ_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_PBM_NW_PRTCPTN_TB', 'P_SYS_ID', 'P_NW_PART_TB', 'P_SYS_ID', 'P_PBM_NW_PRTCPTN_F1', 'P_NW_PART_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_PBM_NW_PRTCPTN_TB', 'P_NW_PART_SK', 'P_NW_PART_TB', 'P_NW_PART_SK', 'P_PBM_NW_PRTCPTN_F1', 'P_NW_PART_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_PREV_MCAID_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_PREV_MCAID_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_PREV_NAM_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_PREV_NAM_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_PROG_INFO_REQ_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_PROG_INFO_REQ_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_PROV_CNTY_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_PROV_CNTY_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSP_PROV_RECIP_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSP_PROV_RECIP_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSP_QSTNR_INITIALED_RESP_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSP_QSTNR_INITIALED_RESP_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSP_QSTNR_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSP_QSTNR_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSTNR_ADVRS_LEGAL_ACTN_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSTNR_ADVRS_LEGAL_ACTN_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSTNR_EXCLSN_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSTNR_EXCLSN_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSTNR_OTHER_STATE_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSTNR_OTHER_STATE_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSTNR_OVR_PMT_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSTNR_OVR_PMT_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_QSTNR_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_QSTNR_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_RA_MEDM_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_RA_MEDM_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_RA_MEDM_TX', 'P_SYS_ID', 'P_RA_MEDM_TB', 'P_SYS_ID', 'P_RA_MEDM_FX1', 'P_RA_MEDM_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_RA_MEDM_TX', 'P_RA_MEDM_SK', 'P_RA_MEDM_TB', 'P_RA_MEDM_SK', 'P_RA_MEDM_FX1', 'P_RA_MEDM_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_RA_MEDM_TX', 'G_CLRG_HOUSE_PHONE_SK', 'G_PHONE_TB', 'G_PHONE_SK', 'P_RA_MEDM_FX2', 'G_PHONE_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_RA_MEDM_TX', 'G_CLRG_HOUSE_EMAIL_SK', 'G_E_ADR_TB', 'G_E_ADR_SK', 'P_RA_MEDM_FX3', 'G_E_ADR_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_REQ_ATTACH_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_REQ_ATTACH_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_REVAL_STAT_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_REVAL_STAT_FN1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_RSK_SCRN_TN', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_RSK_SCRN_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_SPECL_NEED_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_SPECL_NEED_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_SPECL_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_SPECL_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_SVC_TY_CD_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_SVC_TY_CD_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TAX_NTC_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_TAX_NTC_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_CRSE_TB', 'G_NOTE_SET_SK', 'G_NOTE_SET_TB', 'G_NOTE_SET_SK', 'P_TRNG_CRSE_F1', 'G_NOTE_SET_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_RGSTR_TB', 'G_PROV_CMN_ENTY_SK', 'G_CMN_ENTY_TB', 'G_CMN_ENTY_SK', 'P_TRNG_RGSTR_F1', 'G_CMN_ENTY_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_RGSTR_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_SESSN_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_RGSTR_F2', 'P_TRNG_SESSN_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_RGSTR_TB', 'P_TRNG_SESSN_ID', 'P_TRNG_SESSN_TB', 'P_TRNG_SESSN_ID', 'P_TRNG_RGSTR_F2', 'P_TRNG_SESSN_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_SESSN_ATTACH_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_SESSN_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_SESSN_ATTACH_F1', 'P_TRNG_SESSN_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_SESSN_ATTACH_TB', 'P_TRNG_SESSN_ID', 'P_TRNG_SESSN_TB', 'P_TRNG_SESSN_ID', 'P_TRNG_SESSN_ATTACH_F1', 'P_TRNG_SESSN_PK', 2);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_SESSN_ATTACH_TB', 'G_ATTACH_SK', 'G_ATTACH_TB', 'G_ATTACH_SK', 'P_TRNG_SESSN_ATTACH_F2', 'G_CM_ATTACH_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_SESSN_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_CRSE_TB', 'P_TRNG_CRSE_ID', 'P_TRNG_SESSN_F1', 'P_TRNG_CRSE_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TRNG_SESSN_TB', 'G_NOTE_SET_SK', 'G_NOTE_SET_TB', 'G_NOTE_SET_SK', 'P_TRNG_SESSN_F2', 'G_NOTE_SET_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TXNMY_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_TXNMY_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_TY_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_TY_F1', 'P_DTL_PK', 1);
INSERT INTO migration_foreign_keys (module_name, child_table, child_column, parent_table, parent_column, fk_name, pk_name, position_no) VALUES ('Provider', 'P_WEB_DSPLY_TB', 'P_SYS_ID', 'P_DTL_TB', 'P_SYS_ID', 'P_WEB_DSPLY_F1', 'P_DTL_PK', 1);

COMMIT;
