--------------------------------------------------------
--  DDL for Index G_ADR_USG_FX2
--------------------------------------------------------

  CREATE INDEX "NDMMIS73E2"."G_ADR_USG_FX2" ON "NDMMIS73E2"."G_ADR_USG_TB" ("G_ADR_SK") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "Z_M_D_NDMMIS73E2" ;
