import React from 'react';
import Editor from '@monaco-editor/react';
import ActionToolbar from '../../common/ActionToolbar';

export default function SqlEditorTab({ tab }) {
  const defaultSql = `-- [AI Generated] Converted from Oracle Database
-- Source: provider table

CREATE TABLE provider.p_dtl_tb (
    p_sys_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    p_fst_nm VARCHAR(100),
    p_mdl_nm VARCHAR(100),
    p_lst_nm VARCHAR(100),
    p_npi VARCHAR(10),
    g_aud_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    g_aud_add_ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(defaultSql);
  };

  return (
    <div className="h-full flex flex-col bg-bg relative">
      <ActionToolbar 
        title={`${tab.title} - PostgreSQL Dialect`} 
        onCopy={handleCopy} 
        onDownload={() => {}} 
        type="SQL" 
        isEditor={true}
      />
      <div className="flex-1">
        <Editor
          height="100%"
          defaultLanguage="sql"
          theme="vs-dark"
          defaultValue={defaultSql}
          options={{
            minimap: { enabled: true },
            fontSize: 13,
            fontFamily: "'JetBrains Mono', 'Menlo', monospace",
            lineNumbers: 'on',
            scrollBeyondLastLine: false,
            smoothScrolling: true,
            cursorBlinking: "smooth",
            cursorSmoothCaretAnimation: "on",
            formatOnPaste: true,
          }}
        />
      </div>
    </div>
  );
}
